---
body:
  action: text
  ajouterAuteur: text
  besoin: text
  category: number
  chapo: text
  civility: text
  commentId: number
  content: text
  email: email
  first_name: name
  idAuteur: number
  image: image
  last_name: name
  name: text
  password: text
  tel: telephone
  title: text
filters:
  name:
    valid: /^[\p{Latin} -]*$/
    sanitize:
    - regex: /[^\p{Latin} -]/
  email:
    sanitize:
    - regex: /[^\p{Latin}\p{N}@-_.]*/
  text:
    valid: /^[\p{Latin}\p{N}\p{P} -]*$/
    sanitize:
    - regex: /^[^\p{Latin}\p{N}\p{P} -]/
    - avoidSqlInjection
  telephone:
    valid: /^[\p{Latin}\p{N}\p{P} -]*$/
    sanitize:
    - regex: /[^p{N}()+]*/
  number:
    valid: /^[0-9]*$/
    sanitize:
    - regex: /[^0-9+]*/
  image:
    sanitize: